Hmw6
Andrij72/homework pull request #10
Opened 2019-03-13 22:47 UTC by Andrij72

2019-03-13 22:51 UTC, Andrij72 commented
I had hard problems with config gitbush so i"m be late with my  pushing

2019-03-14 08:35 UTC, Taniann requested changes
where is task with Flower shop?

2019-03-14 21:38 UTC, Taniann requested changes
please resolve comments

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/Flowers.java
> +public abstract class Flowers {
use singular noun for name -> Flower

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/Start.java
> +
remove redundant blank line

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/Start.java
> +public class Start {
better name FlowerShopApp

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/FlowerStore.java
> +    private void totalBalance(Flowers[] buket) {
private method write after public ones
[Ordering of class contents](https://mate-academy.github.io/style-guides/java/java.html#s3.4.2-ordering-class-contents)

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/FlowerStore.java
> +    private void totalBalance(Flowers[] buket) {
and [Method names are typically verbs or verb phrases](https://mate-academy.github.io/style-guides/java/java.html#s5.2.3-method-names)

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/Chamomile.java
> +        super(70);
better pass value as constructor param or use constants instead of using "magic numbers"

2019-03-14 21:38 UTC, Taniann commented on src/com/mateakademia/homework/homework6/FlowerStore.java
> +        int QuantityFlowers = rose + chamomile + tulip;
use lowerUpperCase for variable name QuantityFlowers -> quantityFlowers

2019-03-15 07:41 UTC, Taniann approved these changes
good

2019-03-16 17:40 UTC, merged