Add Car and anothter *.java
Andrij72/homework pull request #5
Opened 2019-03-02 07:47 UTC by Andrij72

2019-03-02 07:49 UTC, Andrij72 commented
Small different changers in Car.java

2019-03-02 08:06 UTC, Anderwerty requested changes
Please resolve comments

2019-03-02 08:06 UTC, Anderwerty commented on Car.java
> +    private final int produceDate;
Please use type LocalDate for productDate.

2019-03-02 08:06 UTC, Anderwerty commented on Car.java
> +    public void setNewWheels(int x){
Please, use a better name for the parameter. Example: x->numberOfWheels

2019-03-02 08:06 UTC, Anderwerty commented on Car.java
> +        if ((currentPassNumber == 0) || (wheelCount == 0)){
Optional: it is possible to use the ternary operator.

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +    CarDoor(){
Add access modifier.

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +      IsDoorOpened = false;
False is the default value for the boolean variable. So lines
```
 IsDoorOpened = false;
 IsWindowOpened = false;
```
are redundent.

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +    private boolean IsDoorOpened;
https://mate-academy.github.io/style-guides/java/java.html#s5.2.5-non-constant-field-names

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +    private boolean IsWindowOpened;
The same

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +
A redundant blank line should be removed.

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +
A redundant blank line. Remove it

2019-03-02 08:06 UTC, Anderwerty commented on CarDoor.java
> +
Redundant blank lines. Remove them.

2019-03-02 08:06 UTC, Anderwerty commented on CarWheel.java
> +                System.out.println("It's cann't  create CarWheel");
You will create a new object but tireTag will be 0.

2019-03-02 08:06 UTC, Anderwerty commented on CarWheel.java
> +        private boolean checkTire(double tireTag) {
It seems this method has two responsibility check if value inside of [0,1] and print information.
Let's try to use SOLID principle (S- single responsibility)

2019-03-02 08:06 UTC, Anderwerty commented on CarWheel.java
> +        private double tireTag;
Order:
Constants, fields,...

2019-03-02 12:23 UTC, Anderwerty requested changes

2019-03-02 12:23 UTC, Anderwerty commented on CarWheel.java
> +            if (!result) System.out.println(" Wrong number tire wear, diapason is [0,1].");
https://mate-academy.github.io/style-guides/java/java.html#s4.1.1-braces-always-used
Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement.

2019-03-03 13:51 UTC, Anderwerty approved these changes

2019-03-03 14:01 UTC, merged